const BLOG_POSTS=[
{id:"gardener-or-carpenter",date:"2024-09-12",category:{en:"Parenting & Education",fa:"تربیت و آموزش",ps:"روزنه او زده‌کړه",ar:"التربية والتعليم"},source:"https://ahia74.wordpress.com/2024/09/12/%D8%A8%D8%A7%D8%BA%D8%A8%D8%A7%D9%86-%DB%8C%D8%A7-%D9%86%D8%AC%D8%A7%D8%B1%D8%9F/",title:{en:"Gardener or Carpenter?",fa:"باغبان یا نجار؟!",ps:"بڼوال که ترکاڼ؟",ar:"البستاني أم النجار؟"},excerpt:{en:"Children need patient cultivation, not rigid construction.",fa:"فرزندان به باغبانی نیاز دارند، نه نجاری.",ps:"ماشومان پالنې ته اړتیا لري، نه جبري قالب ته.",ar:"يحتاج الأطفال إلى الرعاية لا إلى التشكيل القسري."},body:{
fa:["فرزندان ما نیازی به نجار ندارند؛ بلکه به باغبانی احتیاج دارند، چون آن‌ها همچون گل هستند. این مفهوم را از کتاب «باغبان و نجار» نوشته آلیسون گوپنیک آموختم.","نجار چوب را طبق طرح خود می‌بُرد، می‌کوبد و شکل می‌دهد؛ اما باغبان به گیاه آب می‌دهد، از آن مراقبت می‌کند و شرایط رشدش را فراهم می‌سازد. هر گیاه به شیوه خود رشد می‌کند و زیبایی متفاوتی می‌آفریند.","والدین نیز باید مانند باغبان باشند: از فرزندان حمایت کنند و زمینه رشد استعدادهایشان را بسازند. تفکر نجاری زمانی آغاز می‌شود که بخواهیم همه چیز را از پیش برای آنان انتخاب کنیم."],
en:["Our children do not need carpenters; they need gardeners, because they are like flowers. I learned this image from Alison Gopnik’s book The Gardener and the Carpenter.","A carpenter cuts and shapes wood according to a fixed design. A gardener instead waters, protects, and creates the conditions for growth. Each plant grows differently and produces its own beauty.","Parents should therefore act like gardeners: support children and create room for their particular abilities. The carpenter mentality begins when we try to choose and predict everything for them."],
ps:["زموږ ماشومان ترکاڼ ته نه، بلکې بڼوال ته اړتیا لري؛ ځکه هغوی د ګلونو په څېر دي. دا تصور مې د الیسن ګوپنیک له «بڼوال او ترکاڼ» کتابه زده کړی.","ترکاڼ لرګی د خپل ټاکلي شکل له مخې پرې کوي او جوړوي؛ خو بڼوال بوټي ته اوبه ورکوي، ساتنه یې کوي او د ودې زمینه ورته برابروي. هر بوټی په خپل ډول وده کوي.","مور او پلار باید د بڼوال په څېر د ماشوم ملاتړ وکړي او د استعداد د ودې چاپېریال ورته جوړ کړي. د ترکاڼ فکر هغه وخت پیلېږي چې د ماشوم هر څه له مخکې موږ وټاکو."],
ar:["لا يحتاج أطفالنا إلى نجّار، بل إلى بستاني؛ فهم كالزهور. تعلمت هذه الصورة من كتاب «البستاني والنجار» لأليسون غوبنيك.","يقطع النجار الخشب ويشكله وفق تصميم ثابت، أما البستاني فيسقي النبات ويحميه ويهيئ له ظروف النمو. ولكل نبتة طريقتها الخاصة في النمو والجمال.","لذلك ينبغي للوالدين أن يكونا كالبستاني: يدعمان الطفل ويوفران مجالاً لمواهبه. وتبدأ عقلية النجار حين نحاول أن نختار له كل شيء مسبقاً."]}},
{id:"peace-that-lasts",date:"2020-01-18",category:{en:"Peace & Society",fa:"صلح و جامعه",ps:"سوله او ټولنه",ar:"السلام والمجتمع"},source:"https://ahia74.wordpress.com/2020/01/18/aziz_hafeez_peace/",title:{en:"How Does Peace Come—and Last?",fa:"صلح چگونه می‌آید و می‌ماند؟",ps:"سوله څنګه راځي او پاتې کېږي؟",ar:"كيف يأتي السلام ويستمر؟"},excerpt:{en:"Sustainable peace begins by strengthening people intellectually, scientifically, and culturally.",fa:"صلح پایدار با توانمندسازی فکری، علمی و فرهنگی مردم آغاز می‌شود.",ps:"تلپاتې سوله د خلکو له فکري، علمي او فرهنګي پیاوړتیا پیلېږي.",ar:"يبدأ السلام المستدام بتمكين الناس فكرياً وعلمياً وثقافياً."},body:{
fa:["در افغانستان، برخی منافع خود را در ادامه جنگ می‌بینند؛ از فروش اسلحه، باج‌گیری و ناامن‌سازی سود می‌برند و انسان‌ها را ابزار خود می‌سازند.","برای آوردن صلح، نخستین و مهم‌ترین کار توانمندکردن مردم از نظر فکری، علمی و فرهنگی است. مردم باید بپذیرند که جنگ راه‌حل نیست؛ تفاوت قومی و زبانی ارزش انسانی ما را کم نمی‌کند؛ و آموزش زنان و کودکان، ایثار و همدیگرپذیری پایه‌های صلح‌اند.","امنیت نعمتی بزرگ است. صلح پایدار تنها با اجماع عمومی مردم واقعی کشور و همکاری عالمان، آموزگاران، دانشگاهیان، دانشجویان و بزرگان قومی ممکن می‌شود. این ملت شایسته صلح، آرامش و آبادانی است."],
en:["In Afghanistan, some actors see personal benefit in continued war. Arms sales, extortion, and deliberate insecurity enrich a few while human beings become their instruments.","The first and most important step toward peace is to strengthen people intellectually, scientifically, and culturally. Society must accept that war is not a solution, that ethnic and linguistic differences do not diminish human worth, and that education for women and children, sacrifice, and mutual acceptance are foundations of peace.","Security is a great blessing. Lasting peace requires a genuine public consensus and cooperation among religious scholars, teachers, universities, students, and community elders. This nation deserves peace, stability, and development."],
ps:["په افغانستان کې ځینې کسان د جګړې په دوام کې خپله ګټه ویني. د وسلو پلور، باج اخیستل او ناامني څو کسان شتمنوي او انسانان د هغوی په وسیلو بدلوي.","د سولې لپاره لومړی او تر ټولو مهم کار د خلکو فکري، علمي او فرهنګي پیاوړتیا ده. ټولنه باید ومني چې جګړه حل نه ده، قومي او ژبني توپیرونه د انسان ارزښت نه کموي، او د ښځو او ماشومانو زده‌کړه، قرباني او یو بل منل د سولې بنسټونه دي.","امنیت لوی نعمت دی. تلپاتې سوله د خلکو رښتینې اجماع او د علماوو، ښوونکو، پوهنتونونو، محصلانو او قومي مشرانو ګډ کار غواړي. دا ملت د سولې، ثبات او آبادۍ وړ دی."],
ar:["يرى بعض الفاعلين في استمرار الحرب مصلحة شخصية؛ فتجارة السلاح والابتزاز وصناعة الفوضى تثري قلةً وتحول البشر إلى أدوات.","الخطوة الأولى والأهم نحو السلام هي تمكين الناس فكرياً وعلمياً وثقافياً. يجب أن يقتنع المجتمع بأن الحرب ليست حلاً، وأن الاختلاف العرقي واللغوي لا ينتقص من قيمة الإنسان، وأن تعليم النساء والأطفال والتضحية وقبول الآخر من أسس السلام.","الأمن نعمة عظيمة. ويتطلب السلام الدائم إجماعاً شعبياً حقيقياً وتعاون العلماء والمعلمين والجامعات والطلاب ووجهاء المجتمع. هذا الشعب يستحق السلام والاستقرار والعمران."]}},
{id:"introduction-to-judaism",date:"2020-03-03",category:{en:"Comparative Religion",fa:"مطالعات ادیان",ps:"د ادیانو مطالعه",ar:"دراسة الأديان"},source:"https://ahia74.wordpress.com/2020/03/03/study_judaism_1/",title:{en:"An Introduction to Judaism",fa:"معرفی یهودیت",ps:"د یهودیت پېژندنه",ar:"مقدمة في اليهودية"},excerpt:{en:"A concise guide to Judaism’s terminology, scriptures, and major modern movements.",fa:"راهنمایی کوتاه درباره اصطلاحات، متون و شاخه‌های مهم یهودیت.",ps:"د یهودیت د اصطلاحاتو، متونو او مهمو څانګو لنډه پېژندنه.",ar:"دليل موجز إلى مصطلحات اليهودية ونصوصها واتجاهاتها الكبرى."},body:{
fa:["یهودیت یکی از ادیان زنده ابراهیمی است. پیروان آن یهودی نامیده می‌شوند و موسی علیه‌السلام در سنت آنان پیامبری محوری است. تورات، تناخ و تلمود از متون مهم دینی آنان‌اند.","سه اصطلاح را باید از هم جدا کرد: عبری زبان تاریخی و دینی یهودیان است؛ اسرائیل نامی است که در سنت‌های ابراهیمی به حضرت یعقوب نسبت داده می‌شود؛ و یهودیت نام دین است.","شاخه‌های مهم معاصر شامل یهودیت ارتودوکس، محافظه‌کار، اصلاح‌طلب، بازسازی‌گرا و اومانیستی یا سکولار است. صهیونیسم برخلاف این شاخه‌های دینی، یک جنبش سیاسی است و نمی‌توان آن را مترادف یهودیت دانست."],
en:["Judaism is a living Abrahamic religion. Its followers are called Jews, and Moses is a central prophet in Jewish tradition. The Torah, Tanakh, and Talmud are among its important religious texts.","Three terms should be distinguished: Hebrew is the historic and religious language of the Jewish people; Israel is a name associated in Abrahamic traditions with Jacob; and Judaism is the name of the religion.","Major modern movements include Orthodox, Conservative, Reform, Reconstructionist, and Humanistic or secular Judaism. Zionism, unlike these religious movements, is political and should not be treated as synonymous with Judaism."],
ps:["یهودیت یو ژوندی ابراهیمي دین دی. پیروان یې یهودیان بلل کېږي، او موسی علیه السلام د هغوی په دود کې مرکزي پیغمبر دی. تورات، تناخ او تلمود د هغوی له مهمو دیني متونو څخه دي.","درې اصطلاحات باید سره بېل شي: عبري د یهودیانو تاریخي او دیني ژبه ده؛ اسرائیل هغه نوم دی چې په ابراهیمي روایتونو کې له یعقوب علیه السلام سره تړل کېږي؛ او یهودیت د دین نوم دی.","مهم معاصر بهیرونه ارتودوکس، محافظه‌کار، اصلاح‌غوښتونکی، بیا رغوونکی او انساني یا سیکولر یهودیت دي. صهیونیزم سیاسي خوځښت دی او باید له یهودیت سره یو شی ونه ګڼل شي."],
ar:["اليهودية دين إبراهيمي حي، وأتباعه هم اليهود، ويُعد موسى عليه السلام نبياً محورياً في تقاليدهم. ومن نصوصهم الدينية المهمة التوراة والتناخ والتلمود.","ينبغي التفريق بين ثلاثة مصطلحات: العبرية لغة اليهود التاريخية والدينية؛ وإسرائيل اسم يرتبط بيعقوب عليه السلام في التقاليد الإبراهيمية؛ واليهودية اسم الدين.","ومن أبرز الاتجاهات الحديثة: الأرثوذكسية والمحافظة والإصلاحية وإعادة البناء والإنسانية أو العلمانية. أما الصهيونية فهي حركة سياسية، ولا يصح اعتبارها مرادفاً لليهودية."]}},
{id:"thinking-is-not-easy",date:"2020-01-24",category:{en:"Ethics & Society",fa:"اخلاق و جامعه",ps:"اخلاق او ټولنه",ar:"الأخلاق والمجتمع"},source:"https://ahia74.wordpress.com/2020/01/24/poorness_in_the_society/",title:{en:"Thinking Is Not So Easy",fa:"تفکر آن‌قدرها هم آسان نیست!",ps:"فکر کول دومره اسانه نه دي!",ar:"التفكير ليس سهلاً إلى هذا الحد"},excerpt:{en:"A short reflection on poverty, public priorities, and moral attention.",fa:"تأملی کوتاه درباره فقر، اولویت‌های عمومی و توجه اخلاقی.",ps:"د فقر، عامه لومړیتوبونو او اخلاقي پاملرنې په اړه لنډ فکر.",ar:"تأمل قصير في الفقر والأولويات العامة والانتباه الأخلاقي."},body:{
fa:["امروز انسان‌های زیادی شب گرسنه سر بر زمین می‌گذارند. برف و باران برای زمین مایه برکت است، اما خبر آمدنش تن تهی‌دستان را می‌لرزاند.","با این حال، ثروت عمومی گاهی برای ساخت‌وسازهای غیرضروری هزینه می‌شود؛ ثروتی که باید مردم را از فقر و تنگدستی نجات دهد.","نیازی به سخن بسیار نیست؛ یک دقیقه تفکر کافی است. اما گویی تفکرکردن آن‌قدرها هم آسان نیست."],
en:["Many people still lie down hungry at night. Snow and rain bless the land, yet their arrival frightens those without shelter or means.","At the same time, public wealth is sometimes spent on unnecessary construction—wealth that should help rescue people from poverty and deprivation.","Many words are unnecessary; one minute of honest thought should be enough. Yet perhaps thinking is not so easy after all."],
ps:["ډېر خلک لا هم شپه وږي پر ځمکه تېروي. واوره او باران ځمکې ته برکت دی، خو د سرپناه او وس نه لرونکو لپاره یې خبر وېره راوړي.","په همدې وخت کې عامه شتمني کله ناکله پر غیر ضروري ودانیو لګېږي؛ هغه شتمني چې باید خلک له فقر او تنګلاسۍ وژغوري.","ډېرو خبرو ته اړتیا نشته؛ یوه دقیقه رښتینی فکر بس دی. خو ښایي فکر کول دومره اسانه نه وي."],
ar:["ما زال كثيرون ينامون جائعين. والثلج والمطر بركة للأرض، لكن خبر قدومهما يرعب من لا يملكون مأوى ولا قدرة.","وفي الوقت نفسه تُنفق الأموال العامة أحياناً على إنشاءات غير ضرورية، مع أنها أولى بإنقاذ الناس من الفقر والحرمان.","لا نحتاج إلى كثرة الكلام؛ تكفي دقيقة من التفكير الصادق. لكن يبدو أن التفكير ليس سهلاً كما نظن."]}},
{id:"no-superman",date:"2017-12-07",category:{en:"Leadership & Renewal",fa:"رهبری و اصلاح",ps:"رهبري او اصلاح",ar:"القيادة والإصلاح"},source:"https://ahia74.wordpress.com/2017/12/07/%D9%86%DB%8C%D8%A7%D8%B2%DB%8C-%D8%A8%D9%87-%D8%B3%D9%88%D9%BE%D8%B1%D9%85%D9%86-%D9%86%DB%8C%D8%B3%D8%AA-%D8%8C%D8%AE%D9%88%D8%AF%D8%AA-%D8%B1%D8%A7-%D8%A7%D8%B5%D9%84%D8%A7%D8%AD-%DA%A9%D9%86/",title:{en:"We Do Not Need Superman—Reform Yourself",fa:"نیازی به سوپرمن نیست؛ خودت را اصلاح کن",ps:"سوپرمن ته اړتیا نشته؛ ځان اصلاح کړه",ar:"لا نحتاج إلى سوبرمان؛ أصلح نفسك"},excerpt:{en:"Civilizational renewal comes from disciplined collective work, not miraculous heroes.",fa:"اصلاح تمدنی از کار منظم و جمعی می‌آید، نه از قهرمانان معجزه‌گر.",ps:"تمدني اصلاح له منظم ګډ کاره راځي، نه له معجزه‌ګر اتل څخه.",ar:"يأتي الإصلاح الحضاري من العمل الجماعي المنظم، لا من الأبطال الخارقين."},body:{
fa:["در کودکی درباره صلاح‌الدین ایوبی می‌شنیدیم و تصور می‌کردیم شخصیتی خارق‌العاده بود که معجزه‌وار آزادی آورد.","اما زمینه پیروزی را اندیشه و کار عالمانی چون ابوحامد غزالی آغاز کرد و خاندان زنگی آن را پرورش داد تا صلاح‌الدین ادامه‌اش داد.","پس به سوپرمن نیاز نداریم؛ به کار منظم، روشمند و نظامی نیاز داریم که به عقل و انسان احترام بگذارد."],
en:["As children, we heard about Salah al-Din and imagined an extraordinary figure who brought liberation almost miraculously.","But the foundations of victory were laid through ideas and sustained work, including scholars such as Abu Hamid al-Ghazali and the efforts of the Zengid dynasty, before Salah al-Din carried the project forward.","We do not need Superman. We need disciplined, methodical work and institutions that respect reason and human dignity."],
ps:["په ماشومتوب کې مو د صلاح‌الدین ایوبي کیسې اورېدې او فکر مو کاوه چې هغه یو خارق‌العاده انسان و چې په معجزه‌یي ډول یې ازادي راوړه.","خو د بریا بنسټ د فکر او دوامدار کار له لارې کېښودل شو؛ د ابو حامد غزالي په څېر علماوو او زنګي کورنۍ زمینه برابره کړه، بیا صلاح‌الدین دغه لاره مخکې یوړه.","موږ سوپرمن ته اړتیا نه لرو؛ منظم او منهجي کار او داسې بنسټونه غواړو چې عقل او انسان ته درناوی وکړي."],
ar:["كنا في طفولتنا نسمع عن صلاح الدين ونتخيله شخصية خارقة جلبت التحرير بصورة تكاد تكون معجزة.","لكن أسس النصر بُنيت بالفكر والعمل المتواصل؛ أسهم علماء مثل أبي حامد الغزالي وجهود الأسرة الزنكية في تهيئة الطريق، ثم واصل صلاح الدين المشروع.","لسنا بحاجة إلى سوبرمان، بل إلى عمل منظم ومنهجي ومؤسسات تحترم العقل وكرامة الإنسان."]}}
];